# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">= 2.2.7"
ENV['VAGRANT_NO_PARALLEL'] = 'yes'
API_VERSION = "2"

require File.dirname(__FILE__)+"/dependency_manager"
require 'yaml'
masters= YAML.load_file('masters.yml')
workers= YAML.load_file('nodes.yml')
# Automatically install required vagrant plugins
check_plugins ["vagrant-reload", "vagrant-vbguest", "vagrant-timezone", "vagrant-disksize"]

Vagrant.configure(API_VERSION) do |config|
  masters.each do | master |
  config.vm.provision "shell", path: master["prerequisites"],:args => ["kubeadmin"]
  # Master
  config.vm.define master["name"] do |kmaster|
    kmaster.vm.box = master["box"]
    #kmaster.disksize.size = '200GB'
    kmaster.vm.hostname = master["hostname"]
    kmaster.vm.network "private_network", ip: master["box_ip"]
    kmaster.vm.provider "virtualbox" do |vb|
      vb.name = master["name"]
      vb.memory = master["memory"]
      vb.cpus = master["cpu"]
    end
    kmaster.vm.provision "shell", path: master["master-provision"],:args =>  ["100.10.10.100"]
    kmaster.vm.provision "shell", path: master["helm-provision"]
    kmaster.vm.provision "shell", path: master["helm-tiller"]
  end
  end

  #NodeCount = 1
  # Worker
  #(1..NodeCount).each do |i|
  workers.each do | worker |
    config.vm.define worker["name"] do |workernode|
      workernode.vm.box = worker["box"]
      workernode.vm.hostname = worker["hostname"]
      workernode.vm.network "private_network", ip: worker["box_ip"]
      workernode.vm.provider "virtualbox" do |vb|
        vb.name = worker["name"]
        vb.memory = worker["memory"]
        vb.cpus = worker["cpu"]
      end
      workernode.vm.provision "shell", path: worker["worker-provision"],:args => ["kubeadmin","kmaster.example.com"]
      workernode.vm.provision "shell", path: worker["helm-provision"]
      workernode.vm.provision "shell", path: worker["addons-provision"],:args => ["100.10.10.100"]
    end
  end
end
