# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">= 2.2.7"
ENV['VAGRANT_NO_PARALLEL'] = 'yes'
API_VERSION = "2"

require File.dirname(__FILE__)+"/dependency_manager"
require 'yaml'
masters= YAML.load_file('masters.yml')
workers= YAML.load_file('nodes.yml')
# Automatically install required vagrant plugins
check_plugins ["vagrant-reload", "vagrant-vbguest", "vagrant-timezone", "vagrant-disksize"]

Vagrant.configure(API_VERSION) do |config|
  masters.each do | master |
  config.vm.provision "shell", path: master["prerequisites"],:args => ["kubeadmin"]
  # Master
  config.vm.define master["name"] do |kmaster|
    kmaster.vm.box = master["box"]
    #kmaster.disksize.size = '200GB'
    kmaster.vm.hostname = master["hostname"]
    kmaster.vm.network "private_network", ip: master["box_ip"]
    kmaster.vm.provider "virtualbox" do |vb|
      vb.name = master["name"]
      vb.memory = master["memory"]
      vb.cpus = master["cpu"]
    end
    kmaster.vm.provision "shell", path: master["master-provision"],:args => master["box_ip"]
    kmaster.vm.provision "shell", path: master["helm-provision"]
    kmaster.vm.provision "shell", path: master["helm-tiller"]
  end
  end

  NodeCount = 1
  # Worker
  (1..NodeCount).each do |i|
    config.vm.define "kworker#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "kworker#{i}.example.com"
      workernode.vm.network "private_network", ip: "100.10.10.10#{i}"
      workernode.vm.provider "virtualbox" do |vb|
        vb.name = "kworker#{i}"
        vb.memory = 1024
        vb.cpus = 2
      end
      workernode.vm.provision "shell", path: "vm-worker/install.sh",:args => ["kubeadmin","kmaster.example.com"]
      workernode.vm.provision "shell", path: "helm/install.sh"
      workernode.vm.provision "shell", path: "addons/install.sh",:args => ["100.10.10.100"]
    end
  end
end
